---
title: Publications
---

## 2024

#### FrugalLight: Symmetry-Aware Cyclic Heterogeneous Intersection Control using Deep RL with Model Compression, Distillation & Domain Knowledge

**Sachin Chauhan**,Rijurekha Sen. In ACM-JCSS, 2024

#### WebLight: Deep RL based Multi-modal Intersection Control in Developing Countries without Reliable Cameras <br>

**Sachin Chauhan**,Rijurekha Sen. In ACM-COMPASS, 2024

## 2023

#### AirDelhi: Fine-Grained Spatio-Temporal Particulate Matter Dataset From Delhi For ML based Modeling

**Sachin Chauhan**,Zeel Patel,Sayan Ranu,Rijurekha Sen,Nipun Batra. In NeurIPS, 2023

#### RealLight: DRL based Intersection Control in Developing Countries without Traffic Simulators

**Sachin Chauhan**,Rijurekha Sen. In NeurIPS, 2023 (Workshop on Computational Sustainability)

## 2022

#### DynCNN: Application Dynamism and Ambient Temperature Aware Neural Network Scheduler in Edge Devices for Traffic Control

Omais Shafi, **Sachin Chauhan**, Gayathri Ananthanarayanan, Rijurekha Sen. In COMPASS, 2022

## 2020

#### EcoLight: Intersection Control in Developing Regions Under Extreme Budget and Network Constraints

**Sachin Chauhan**,Kashish Bansal,Rijurekha Sen. In NeurIPS, 2020
